# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160404_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesubject',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
