# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160404_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField(max_length=200)),
                ('cos_url', models.CharField(default='', max_length=200)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoubanTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=50)),
                ('author_url', models.CharField(max_length=200)),
                ('user_img_small', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Search_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('searchCount', models.IntegerField()),
                ('zhihu_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZhihuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZhihuQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('author_url', models.CharField(max_length=200)),
                ('title', models.CharField(default='', max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_question', to='blog.ZoneSubject')),
            ],
        ),
        migrations.CreateModel(
            name='ZhihuSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('zhihu_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='zhihuimage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_image', to='blog.ZhihuQuestion'),
        ),
        migrations.AddField(
            model_name='doubanimage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_image', to='blog.DoubanTopic'),
        ),
    ]
