# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_doubantopic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihuquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_question', to='blog.ZhihuSubject'),
        ),
    ]
