# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160404_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubantopic',
            name='create_time',
            field=models.CharField(max_length=20),
        ),
    ]
