# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160404_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubantopic',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
