# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_doubantopic_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanimage',
            name='cos_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='zhihuquestion',
            name='author_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
