# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160406_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='hide_content',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
