# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160406_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
