# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_record',
            name='searchCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='search_record',
            name='zhihu_type',
            field=models.IntegerField(blank=True),
        ),
    ]
