# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
