# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160419_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesubject',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
